version: "3.8"
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama-server:11434
    volumes:
      - open-webui:/app/backend/data
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  ollama:
    image: ollama/ollama:latest  
    container_name: ollama-server
    ports:
      - "11434:11434" 
    volumes:
      - ollama:/root/.ollama
    restart: always

volumes:
  open-webui:
  ollama:
