
services:
  mysql:
    image: mysql:5.7
    container_name: zabbix-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix123
    volumes:
      - mysql_data:/var/lib/mysql

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-5.4-latest
    container_name: zabbix-server
    depends_on:
      - mysql
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix123
    ports:
      - "10051:10051"

  zabbix-web-apache-mysql:
    image: zabbix/zabbix-web-apache-mysql:alpine-5.4-latest
    container_name: zabbix-web
    depends_on:
      - zabbix-server
      - mysql
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix123
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "Europe/Riga"
    ports:
      - "8080:80"

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-5.4-latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server



volumes:
  mysql_data:

