services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: always
    ports:
      - "81:80"
      - "8181:8080"
      - "8182:8443"
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 127.0.0.1
      NEXTCLOUD_URL: https://nc.portkeylabs.net
      SKIP_DOMAIN_VALIDATION: "true"
      DISABLE_LETS_ENCRYPT: "true"
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nextcloud_aio_mastercontainer: